/**
 * Export contract ABIs and addresses for Scaffold-ETH 2 UI.
 *
 * Reads deployment.json + Hardhat artifacts and generates
 * the externalContracts.ts file for the SE2 nextjs package.
 *
 * Usage:
 *   node scripts/export-abis.js
 */

const fs = require("fs");
const path = require("path");

const ARTIFACTS_DIR = path.join(__dirname, "..", "artifacts", "contracts");
const DEPLOYMENT_FILE = path.join(__dirname, "..", "deployment.json");
const OUTPUT_FILE = path.join(__dirname, "..", "..", "ui", "packages", "nextjs", "contracts", "externalContracts.ts");

const CONTRACTS = ["KeyRegistry", "CrossChainBloomFilter", "ImageAuthResolver", "ReputationRegistry"];

function loadABI(contractName) {
  const artifactPath = path.join(ARTIFACTS_DIR, `${contractName}.sol`, `${contractName}.json`);
  if (!fs.existsSync(artifactPath)) {
    console.error(`Artifact not found: ${artifactPath}`);
    console.error(`Run 'npx hardhat compile' first.`);
    process.exit(1);
  }
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
  return artifact.abi;
}

function main() {
  // Load deployment addresses
  let deployment = {};
  if (fs.existsSync(DEPLOYMENT_FILE)) {
    deployment = JSON.parse(fs.readFileSync(DEPLOYMENT_FILE, "utf8"));
    console.log("Loaded deployment.json:", deployment.network, deployment.timestamp);
  } else {
    console.log("No deployment.json found. Using placeholder addresses.");
    console.log("Run 'npx hardhat run scripts/deploy.js --network localhost' first.");
  }

  // Map contract names to deployment keys
  const addressMap = {
    KeyRegistry: deployment.keyRegistry || "0x0000000000000000000000000000000000000000",
    CrossChainBloomFilter: deployment.bloomFilter || "0x0000000000000000000000000000000000000000",
    ImageAuthResolver: deployment.resolver || "0x0000000000000000000000000000000000000000",
    ReputationRegistry: deployment.reputationRegistry || "0x0000000000000000000000000000000000000000",
  };

  // Load ABIs
  const contracts = {};
  for (const name of CONTRACTS) {
    const abi = loadABI(name);
    const address = addressMap[name];
    if (address === "0x0000000000000000000000000000000000000000") {
      console.log(`  ${name}: no address (skipping)`);
      continue;
    }
    contracts[name] = { address, abi };
    console.log(`  ${name}: ${address} (${abi.length} ABI entries)`);
  }

  // Generate externalContracts.ts
  // chainId 31337 = localhost/hardhat
  const output = `import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

/**
 * Auto-generated by ethereum-ledger/scripts/export-abis.js
 * Timestamp: ${new Date().toISOString()}
 *
 * Contains ABIs and addresses for our image authentication contracts.
 * Update by re-running: cd ethereum-ledger && node scripts/export-abis.js
 */
const externalContracts = {
  // Hardhat localhost
  31337: {
${Object.entries(contracts)
  .map(
    ([name, { address, abi }]) =>
      `    ${name}: {\n      address: "${address}",\n      abi: ${JSON.stringify(abi, null, 6).split("\n").join("\n      ")},\n    }`
  )
  .join(",\n")}
  },
  // Base Sepolia (update addresses after testnet deployment)
  84532: {
${Object.entries(contracts)
  .map(
    ([name, { address, abi }]) =>
      `    ${name}: {\n      address: "${address}",\n      abi: ${JSON.stringify(abi, null, 6).split("\n").join("\n      ")},\n    }`
  )
  .join(",\n")}
  },
} as const;

export default externalContracts satisfies GenericContractsDeclaration;
`;

  fs.writeFileSync(OUTPUT_FILE, output);
  console.log(`\nWritten to: ${OUTPUT_FILE}`);
  console.log(`Contains ${Object.keys(contracts).length} contracts for chainIds 31337, 84532`);
}

main();
