import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

/**
 * Auto-generated by ethereum-ledger/scripts/export-abis.js
 * Timestamp: 2026-03-14T19:33:35.783Z
 *
 * Contains ABIs and addresses for our image authentication contracts.
 * Update by re-running: cd ethereum-ledger && node scripts/export-abis.js
 */
const externalContracts = {
  // Hardhat localhost
  31337: {
    KeyRegistry: {
      address: "0x0DCd1Bf9A1b36cE34237eEaFef220932846BCD82",
      abi: [
            {
                  "anonymous": false,
                  "inputs": [
                        {
                              "indexed": true,
                              "internalType": "address",
                              "name": "user",
                              "type": "address"
                        },
                        {
                              "indexed": true,
                              "internalType": "uint256",
                              "name": "keyIndex",
                              "type": "uint256"
                        },
                        {
                              "indexed": false,
                              "internalType": "bytes",
                              "name": "publicKey",
                              "type": "bytes"
                        },
                        {
                              "indexed": false,
                              "internalType": "uint8",
                              "name": "scheme",
                              "type": "uint8"
                        }
                  ],
                  "name": "KeyActivated",
                  "type": "event"
            },
            {
                  "anonymous": false,
                  "inputs": [
                        {
                              "indexed": true,
                              "internalType": "address",
                              "name": "user",
                              "type": "address"
                        },
                        {
                              "indexed": true,
                              "internalType": "uint256",
                              "name": "keyIndex",
                              "type": "uint256"
                        },
                        {
                              "indexed": false,
                              "internalType": "uint64",
                              "name": "revokedAt",
                              "type": "uint64"
                        }
                  ],
                  "name": "KeyRevoked",
                  "type": "event"
            },
            {
                  "inputs": [
                        {
                              "internalType": "address",
                              "name": "",
                              "type": "address"
                        }
                  ],
                  "name": "activeKeyIndex",
                  "outputs": [
                        {
                              "internalType": "uint256",
                              "name": "",
                              "type": "uint256"
                        }
                  ],
                  "stateMutability": "view",
                  "type": "function"
            },
            {
                  "inputs": [
                        {
                              "internalType": "address",
                              "name": "user",
                              "type": "address"
                        },
                        {
                              "internalType": "uint256",
                              "name": "index",
                              "type": "uint256"
                        }
                  ],
                  "name": "getKey",
                  "outputs": [
                        {
                              "internalType": "bytes",
                              "name": "publicKey",
                              "type": "bytes"
                        },
                        {
                              "internalType": "uint8",
                              "name": "scheme",
                              "type": "uint8"
                        },
                        {
                              "internalType": "uint64",
                              "name": "activatedAt",
                              "type": "uint64"
                        },
                        {
                              "internalType": "uint64",
                              "name": "revokedAt",
                              "type": "uint64"
                        }
                  ],
                  "stateMutability": "view",
                  "type": "function"
            },
            {
                  "inputs": [
                        {
                              "internalType": "bytes",
                              "name": "publicKey",
                              "type": "bytes"
                        }
                  ],
                  "name": "isKeyCurrentlyValid",
                  "outputs": [
                        {
                              "internalType": "bool",
                              "name": "",
                              "type": "bool"
                        }
                  ],
                  "stateMutability": "view",
                  "type": "function"
            },
            {
                  "inputs": [
                        {
                              "internalType": "bytes",
                              "name": "publicKey",
                              "type": "bytes"
                        },
                        {
                              "internalType": "uint64",
                              "name": "timestamp",
                              "type": "uint64"
                        }
                  ],
                  "name": "isKeyValidAt",
                  "outputs": [
                        {
                              "internalType": "bool",
                              "name": "",
                              "type": "bool"
                        }
                  ],
                  "stateMutability": "view",
                  "type": "function"
            },
            {
                  "inputs": [
                        {
                              "internalType": "address",
                              "name": "user",
                              "type": "address"
                        }
                  ],
                  "name": "keyCount",
                  "outputs": [
                        {
                              "internalType": "uint256",
                              "name": "",
                              "type": "uint256"
                        }
                  ],
                  "stateMutability": "view",
                  "type": "function"
            },
            {
                  "inputs": [
                        {
                              "internalType": "bytes32",
                              "name": "",
                              "type": "bytes32"
                        }
                  ],
                  "name": "pkIndex",
                  "outputs": [
                        {
                              "internalType": "uint256",
                              "name": "",
                              "type": "uint256"
                        }
                  ],
                  "stateMutability": "view",
                  "type": "function"
            },
            {
                  "inputs": [
                        {
                              "internalType": "bytes32",
                              "name": "",
                              "type": "bytes32"
                        }
                  ],
                  "name": "pkOwner",
                  "outputs": [
                        {
                              "internalType": "address",
                              "name": "",
                              "type": "address"
                        }
                  ],
                  "stateMutability": "view",
                  "type": "function"
            },
            {
                  "inputs": [
                        {
                              "internalType": "bytes",
                              "name": "publicKey",
                              "type": "bytes"
                        },
                        {
                              "internalType": "uint8",
                              "name": "scheme",
                              "type": "uint8"
                        }
                  ],
                  "name": "registerKey",
                  "outputs": [],
                  "stateMutability": "nonpayable",
                  "type": "function"
            },
            {
                  "inputs": [
                        {
                              "internalType": "uint256",
                              "name": "keyIndex",
                              "type": "uint256"
                        }
                  ],
                  "name": "revokeKey",
                  "outputs": [],
                  "stateMutability": "nonpayable",
                  "type": "function"
            },
            {
                  "inputs": [
                        {
                              "internalType": "address",
                              "name": "",
                              "type": "address"
                        },
                        {
                              "internalType": "uint256",
                              "name": "",
                              "type": "uint256"
                        }
                  ],
                  "name": "signingKeys",
                  "outputs": [
                        {
                              "internalType": "bytes",
                              "name": "publicKey",
                              "type": "bytes"
                        },
                        {
                              "internalType": "uint8",
                              "name": "scheme",
                              "type": "uint8"
                        },
                        {
                              "internalType": "uint64",
                              "name": "activatedAt",
                              "type": "uint64"
                        },
                        {
                              "internalType": "uint64",
                              "name": "revokedAt",
                              "type": "uint64"
                        },
                        {
                              "internalType": "bytes32",
                              "name": "pkHash",
                              "type": "bytes32"
                        }
                  ],
                  "stateMutability": "view",
                  "type": "function"
            }
      ],
    },
    CrossChainBloomFilter: {
      address: "0x9A676e781A523b5d0C0e43731313A708CB607508",
      abi: [
            {
                  "inputs": [],
                  "stateMutability": "nonpayable",
                  "type": "constructor"
            },
            {
                  "anonymous": false,
                  "inputs": [
                        {
                              "indexed": false,
                              "internalType": "uint256",
                              "name": "newEntries",
                              "type": "uint256"
                        },
                        {
                              "indexed": false,
                              "internalType": "bytes32",
                              "name": "sourceChainId",
                              "type": "bytes32"
                        }
                  ],
                  "name": "BloomSynced",
                  "type": "event"
            },
            {
                  "anonymous": false,
                  "inputs": [
                        {
                              "indexed": true,
                              "internalType": "bytes32",
                              "name": "pHashSaltKey",
                              "type": "bytes32"
                        }
                  ],
                  "name": "BloomUpdated",
                  "type": "event"
            },
            {
                  "inputs": [
                        {
                              "internalType": "bytes32",
                              "name": "pHashSaltKey",
                              "type": "bytes32"
                        }
                  ],
                  "name": "add",
                  "outputs": [],
                  "stateMutability": "nonpayable",
                  "type": "function"
            },
            {
                  "inputs": [
                        {
                              "internalType": "address",
                              "name": "adder",
                              "type": "address"
                        }
                  ],
                  "name": "authorizeAdder",
                  "outputs": [],
                  "stateMutability": "nonpayable",
                  "type": "function"
            },
            {
                  "inputs": [
                        {
                              "internalType": "address",
                              "name": "",
                              "type": "address"
                        }
                  ],
                  "name": "authorizedAdders",
                  "outputs": [
                        {
                              "internalType": "bool",
                              "name": "",
                              "type": "bool"
                        }
                  ],
                  "stateMutability": "view",
                  "type": "function"
            },
            {
                  "inputs": [
                        {
                              "internalType": "uint256",
                              "name": "",
                              "type": "uint256"
                        }
                  ],
                  "name": "bloomFilter",
                  "outputs": [
                        {
                              "internalType": "uint256",
                              "name": "",
                              "type": "uint256"
                        }
                  ],
                  "stateMutability": "view",
                  "type": "function"
            },
            {
                  "inputs": [],
                  "name": "entryCount",
                  "outputs": [
                        {
                              "internalType": "uint256",
                              "name": "",
                              "type": "uint256"
                        }
                  ],
                  "stateMutability": "view",
                  "type": "function"
            },
            {
                  "inputs": [
                        {
                              "internalType": "bytes32",
                              "name": "pHashSaltKey",
                              "type": "bytes32"
                        }
                  ],
                  "name": "mightContain",
                  "outputs": [
                        {
                              "internalType": "bool",
                              "name": "",
                              "type": "bool"
                        }
                  ],
                  "stateMutability": "view",
                  "type": "function"
            },
            {
                  "inputs": [],
                  "name": "owner",
                  "outputs": [
                        {
                              "internalType": "address",
                              "name": "",
                              "type": "address"
                        }
                  ],
                  "stateMutability": "view",
                  "type": "function"
            },
            {
                  "inputs": [
                        {
                              "internalType": "bytes32[]",
                              "name": "pHashSaltKeys",
                              "type": "bytes32[]"
                        },
                        {
                              "internalType": "bytes32",
                              "name": "sourceChainId",
                              "type": "bytes32"
                        }
                  ],
                  "name": "syncFromChain",
                  "outputs": [],
                  "stateMutability": "nonpayable",
                  "type": "function"
            }
      ],
    }
  },
  // Base Sepolia (update addresses after testnet deployment)
  84532: {
    KeyRegistry: {
      address: "0x0DCd1Bf9A1b36cE34237eEaFef220932846BCD82",
      abi: [
            {
                  "anonymous": false,
                  "inputs": [
                        {
                              "indexed": true,
                              "internalType": "address",
                              "name": "user",
                              "type": "address"
                        },
                        {
                              "indexed": true,
                              "internalType": "uint256",
                              "name": "keyIndex",
                              "type": "uint256"
                        },
                        {
                              "indexed": false,
                              "internalType": "bytes",
                              "name": "publicKey",
                              "type": "bytes"
                        },
                        {
                              "indexed": false,
                              "internalType": "uint8",
                              "name": "scheme",
                              "type": "uint8"
                        }
                  ],
                  "name": "KeyActivated",
                  "type": "event"
            },
            {
                  "anonymous": false,
                  "inputs": [
                        {
                              "indexed": true,
                              "internalType": "address",
                              "name": "user",
                              "type": "address"
                        },
                        {
                              "indexed": true,
                              "internalType": "uint256",
                              "name": "keyIndex",
                              "type": "uint256"
                        },
                        {
                              "indexed": false,
                              "internalType": "uint64",
                              "name": "revokedAt",
                              "type": "uint64"
                        }
                  ],
                  "name": "KeyRevoked",
                  "type": "event"
            },
            {
                  "inputs": [
                        {
                              "internalType": "address",
                              "name": "",
                              "type": "address"
                        }
                  ],
                  "name": "activeKeyIndex",
                  "outputs": [
                        {
                              "internalType": "uint256",
                              "name": "",
                              "type": "uint256"
                        }
                  ],
                  "stateMutability": "view",
                  "type": "function"
            },
            {
                  "inputs": [
                        {
                              "internalType": "address",
                              "name": "user",
                              "type": "address"
                        },
                        {
                              "internalType": "uint256",
                              "name": "index",
                              "type": "uint256"
                        }
                  ],
                  "name": "getKey",
                  "outputs": [
                        {
                              "internalType": "bytes",
                              "name": "publicKey",
                              "type": "bytes"
                        },
                        {
                              "internalType": "uint8",
                              "name": "scheme",
                              "type": "uint8"
                        },
                        {
                              "internalType": "uint64",
                              "name": "activatedAt",
                              "type": "uint64"
                        },
                        {
                              "internalType": "uint64",
                              "name": "revokedAt",
                              "type": "uint64"
                        }
                  ],
                  "stateMutability": "view",
                  "type": "function"
            },
            {
                  "inputs": [
                        {
                              "internalType": "bytes",
                              "name": "publicKey",
                              "type": "bytes"
                        }
                  ],
                  "name": "isKeyCurrentlyValid",
                  "outputs": [
                        {
                              "internalType": "bool",
                              "name": "",
                              "type": "bool"
                        }
                  ],
                  "stateMutability": "view",
                  "type": "function"
            },
            {
                  "inputs": [
                        {
                              "internalType": "bytes",
                              "name": "publicKey",
                              "type": "bytes"
                        },
                        {
                              "internalType": "uint64",
                              "name": "timestamp",
                              "type": "uint64"
                        }
                  ],
                  "name": "isKeyValidAt",
                  "outputs": [
                        {
                              "internalType": "bool",
                              "name": "",
                              "type": "bool"
                        }
                  ],
                  "stateMutability": "view",
                  "type": "function"
            },
            {
                  "inputs": [
                        {
                              "internalType": "address",
                              "name": "user",
                              "type": "address"
                        }
                  ],
                  "name": "keyCount",
                  "outputs": [
                        {
                              "internalType": "uint256",
                              "name": "",
                              "type": "uint256"
                        }
                  ],
                  "stateMutability": "view",
                  "type": "function"
            },
            {
                  "inputs": [
                        {
                              "internalType": "bytes32",
                              "name": "",
                              "type": "bytes32"
                        }
                  ],
                  "name": "pkIndex",
                  "outputs": [
                        {
                              "internalType": "uint256",
                              "name": "",
                              "type": "uint256"
                        }
                  ],
                  "stateMutability": "view",
                  "type": "function"
            },
            {
                  "inputs": [
                        {
                              "internalType": "bytes32",
                              "name": "",
                              "type": "bytes32"
                        }
                  ],
                  "name": "pkOwner",
                  "outputs": [
                        {
                              "internalType": "address",
                              "name": "",
                              "type": "address"
                        }
                  ],
                  "stateMutability": "view",
                  "type": "function"
            },
            {
                  "inputs": [
                        {
                              "internalType": "bytes",
                              "name": "publicKey",
                              "type": "bytes"
                        },
                        {
                              "internalType": "uint8",
                              "name": "scheme",
                              "type": "uint8"
                        }
                  ],
                  "name": "registerKey",
                  "outputs": [],
                  "stateMutability": "nonpayable",
                  "type": "function"
            },
            {
                  "inputs": [
                        {
                              "internalType": "uint256",
                              "name": "keyIndex",
                              "type": "uint256"
                        }
                  ],
                  "name": "revokeKey",
                  "outputs": [],
                  "stateMutability": "nonpayable",
                  "type": "function"
            },
            {
                  "inputs": [
                        {
                              "internalType": "address",
                              "name": "",
                              "type": "address"
                        },
                        {
                              "internalType": "uint256",
                              "name": "",
                              "type": "uint256"
                        }
                  ],
                  "name": "signingKeys",
                  "outputs": [
                        {
                              "internalType": "bytes",
                              "name": "publicKey",
                              "type": "bytes"
                        },
                        {
                              "internalType": "uint8",
                              "name": "scheme",
                              "type": "uint8"
                        },
                        {
                              "internalType": "uint64",
                              "name": "activatedAt",
                              "type": "uint64"
                        },
                        {
                              "internalType": "uint64",
                              "name": "revokedAt",
                              "type": "uint64"
                        },
                        {
                              "internalType": "bytes32",
                              "name": "pkHash",
                              "type": "bytes32"
                        }
                  ],
                  "stateMutability": "view",
                  "type": "function"
            }
      ],
    },
    CrossChainBloomFilter: {
      address: "0x9A676e781A523b5d0C0e43731313A708CB607508",
      abi: [
            {
                  "inputs": [],
                  "stateMutability": "nonpayable",
                  "type": "constructor"
            },
            {
                  "anonymous": false,
                  "inputs": [
                        {
                              "indexed": false,
                              "internalType": "uint256",
                              "name": "newEntries",
                              "type": "uint256"
                        },
                        {
                              "indexed": false,
                              "internalType": "bytes32",
                              "name": "sourceChainId",
                              "type": "bytes32"
                        }
                  ],
                  "name": "BloomSynced",
                  "type": "event"
            },
            {
                  "anonymous": false,
                  "inputs": [
                        {
                              "indexed": true,
                              "internalType": "bytes32",
                              "name": "pHashSaltKey",
                              "type": "bytes32"
                        }
                  ],
                  "name": "BloomUpdated",
                  "type": "event"
            },
            {
                  "inputs": [
                        {
                              "internalType": "bytes32",
                              "name": "pHashSaltKey",
                              "type": "bytes32"
                        }
                  ],
                  "name": "add",
                  "outputs": [],
                  "stateMutability": "nonpayable",
                  "type": "function"
            },
            {
                  "inputs": [
                        {
                              "internalType": "address",
                              "name": "adder",
                              "type": "address"
                        }
                  ],
                  "name": "authorizeAdder",
                  "outputs": [],
                  "stateMutability": "nonpayable",
                  "type": "function"
            },
            {
                  "inputs": [
                        {
                              "internalType": "address",
                              "name": "",
                              "type": "address"
                        }
                  ],
                  "name": "authorizedAdders",
                  "outputs": [
                        {
                              "internalType": "bool",
                              "name": "",
                              "type": "bool"
                        }
                  ],
                  "stateMutability": "view",
                  "type": "function"
            },
            {
                  "inputs": [
                        {
                              "internalType": "uint256",
                              "name": "",
                              "type": "uint256"
                        }
                  ],
                  "name": "bloomFilter",
                  "outputs": [
                        {
                              "internalType": "uint256",
                              "name": "",
                              "type": "uint256"
                        }
                  ],
                  "stateMutability": "view",
                  "type": "function"
            },
            {
                  "inputs": [],
                  "name": "entryCount",
                  "outputs": [
                        {
                              "internalType": "uint256",
                              "name": "",
                              "type": "uint256"
                        }
                  ],
                  "stateMutability": "view",
                  "type": "function"
            },
            {
                  "inputs": [
                        {
                              "internalType": "bytes32",
                              "name": "pHashSaltKey",
                              "type": "bytes32"
                        }
                  ],
                  "name": "mightContain",
                  "outputs": [
                        {
                              "internalType": "bool",
                              "name": "",
                              "type": "bool"
                        }
                  ],
                  "stateMutability": "view",
                  "type": "function"
            },
            {
                  "inputs": [],
                  "name": "owner",
                  "outputs": [
                        {
                              "internalType": "address",
                              "name": "",
                              "type": "address"
                        }
                  ],
                  "stateMutability": "view",
                  "type": "function"
            },
            {
                  "inputs": [
                        {
                              "internalType": "bytes32[]",
                              "name": "pHashSaltKeys",
                              "type": "bytes32[]"
                        },
                        {
                              "internalType": "bytes32",
                              "name": "sourceChainId",
                              "type": "bytes32"
                        }
                  ],
                  "name": "syncFromChain",
                  "outputs": [],
                  "stateMutability": "nonpayable",
                  "type": "function"
            }
      ],
    }
  },
} as const;

export default externalContracts satisfies GenericContractsDeclaration;
